driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]
- name: centos-5.11
- name: centos-6.7
- name: centos-7.1
suites:
- name: default
  run_list: ["recipe[sqlite]"]
  attributes: {}
